latency-wait: "10"
jobscript: "lsf_jobscript.sh"
use-conda: "True"
use-singularity: "True"
printshellcmds: "True"
restart-times: "0"
jobs: "2000"
cluster: "lsf_submit.py"
cluster-status: "lsf_status.py"
max-jobs-per-second: "5"
max-status-checks-per-second: "5"